const Elementals = [
  { id: '31', name: 'First Elemental Master', screen: '', image: require('../../assets/Armor/ElementalArmor/FirstElementalMaster.jpg'), clickable: true },
  { id: '32', name: 'Master Of Creation', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfCreation.jpg'), clickable: true },
  { id: '33', name: 'Creation Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/CreationElemental3.jpg'), clickable: true },
  { id: '34', name: 'Creation Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/CreationElemental.jpg'), clickable: true },
  { id: '35', name: 'Creation Elemental 3', screen: '', image: require('../../assets/Armor/ElementalArmor/CreationElemental2.jpg'), clickable: true },
  { id: '36', name: 'GoldenPower Elemental Master', screen: '', image: require('../../assets/Armor/ElementalArmor/GoldenPowerElementalMaster.jpg'), clickable: true },
  { id: '37', name: 'GoldenPower Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/GoldenPowerElemental.jpg'), clickable: true },
  { id: '38', name: 'Master Of Destruction', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfDestruction.jpg'), clickable: true },
  { id: '39', name: 'Destruction Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/DestructionElemental3.jpg'), clickable: true },
  { id: '40', name: 'Destruction Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/DestructionElemental.jpg'), clickable: true },
  { id: '41', name: 'Destruction Elemental 3', screen: '', image: require('../../assets/Armor/ElementalArmor/DestructionElemental2.jpg'), clickable: true },
  { id: '42', name: 'DragonPower Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/DragonPowerElemental.jpg'), clickable: true },
  { id: '43', name: 'DragonPower Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/DragonPowerElemental2.jpg'), clickable: true },
  { id: '44', name: 'OniPower Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/OniPowerElemental.jpg'), clickable: true },
  { id: '45', name: 'OniPower Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/OniPowerElemental2.jpg'), clickable: true },
  { id: '46', name: 'Master Of Fire', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfFire.jpg'), clickable: true },
  { id: '47', name: 'Fire Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/FireElemental.jpg'), clickable: true },
  { id: '48', name: 'Master Of Lightning', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfLightning.jpg'), clickable: true },
  { id: '49', name: 'Lightning Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/LightningELemental.jpg'), clickable: true },
  { id: '50', name: 'Master Of Ice', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfIce.jpg'), clickable: true },
  { id: '51', name: 'Ice Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/IceElemental.jpg'), clickable: true },
  { id: '52', name: 'Ice Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/IceElemental2.jpg'), clickable: true },
  { id: '53', name: 'Ice Elemental 3', screen: '', image: require('../../assets/Armor/ElementalArmor/IceElemental3.jpg'), clickable: true },
  { id: '54', name: 'Master Of Earth', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfEarth.jpg'), clickable: true },
  { id: '55', name: 'Earth Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/EarthElemental.jpg'), clickable: true },
  { id: '56', name: 'Master Of Water', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfWater.jpg'), clickable: true },
  { id: '57', name: 'Water Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/WaterElemental.jpg'), clickable: true },
  { id: '58', name: 'Master Of Energy', screen: '', image: require('../../assets/Armor/ElementalArmor/EnergyElemental4.jpg'), clickable: true },
  { id: '59', name: 'Energy Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfEnergy.jpg'), clickable: true },
  { id: '60', name: 'Energy Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/EnergyElemental.jpg'), clickable: true },
  { id: '61', name: 'Energy Elemental 3', screen: '', image: require('../../assets/Armor/ElementalArmor/EnergyElemental2.jpg'), clickable: true },
  { id: '62', name: 'Energy Elemental 4', screen: '', image: require('../../assets/Armor/ElementalArmor/EnergyElemental3.jpg'), clickable: true },
  { id: '63', name: 'Master Of Wind', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfWind.jpg'), clickable: true },
  { id: '64', name: 'Wind Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/WindElemental.jpg'), clickable: true },
  { id: '65', name: 'Master Of Shadow', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfShadow.jpg'), clickable: true },
  { id: '66', name: 'Shadow Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/ShadowElemental.jpg'), clickable: true },
  { id: '67', name: 'Master Of Light', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfLight.jpg'), clickable: true },
  { id: '68', name: 'Light Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/LightElemental.jpg'), clickable: true },
  { id: '69', name: 'Light Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/LightElemental2.jpg'), clickable: true },
  { id: '70', name: 'Light Elemental 3', screen: '', image: require('../../assets/Armor/ElementalArmor/LightElemental3.jpg'), clickable: true },
  { id: '71', name: 'Master Of Metal', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfMetal.jpg'), clickable: true },
  { id: '72', name: 'Metal Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/MetalElemental.jpg'), clickable: true },
  { id: '73', name: 'Master Of Poison', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfPoison.jpg'), clickable: true },
  { id: '74', name: 'Poison Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/PoisonElemental.jpg'), clickable: true },
  { id: '75', name: 'Master Of Nature', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfNature.jpg'), clickable: true },
  { id: '76', name: 'Nature Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/NatureElemental.jpg'), clickable: true },
  { id: '77', name: 'Master Of Mind', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfMind.jpg'), clickable: true },
  { id: '78', name: 'Mind Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/MindElemental.jpg'), clickable: true },
  { id: '79', name: 'Master Of Speed', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfSpeed.jpg'), clickable: true },
  { id: '80', name: 'Speed Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/SpeedElemental.jpg'), clickable: true },
  { id: '81', name: 'Master Of Gravity', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfGravity.jpg'), clickable: true },
  { id: '82', name: 'Gravity Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/GravityElemental.jpg'), clickable: true },
  { id: '83', name: 'Master Of Amber', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfAmber.jpg'), clickable: true },
  { id: '84', name: 'Amber Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/AmberElemental.jpg'), clickable: true },
  { id: '85', name: 'Master Of Smoke', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfSmoke.jpg'), clickable: true },
  { id: '86', name: 'Smoke Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/SmokeElemental.jpg'), clickable: true },
  { id: '87', name: 'Master Of Sound', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfSound.jpg'), clickable: true },
  { id: '88', name: 'Sound Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/SoundElemental.jpg'), clickable: true },
  { id: '89', name: 'Master Of Form', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfForm.jpg'), clickable: true },
  { id: '90', name: 'Form Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/FormElemental.jpg'), clickable: true },
  { id: '91', name: 'Master Of Time', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfTime.jpg'), clickable: true },
  { id: '92', name: 'Time Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/TimeElemental.jpg'), clickable: true },
  { id: '93', name: 'Time Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/TimeElemental2.jpg'), clickable: true },
  { id: '94', name: 'Time Elemental 3', screen: '', image: require('../../assets/Armor/ElementalArmor/TimeElemental3.jpg'), clickable: true },
  { id: '95', name: 'Master Of Darkness', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfDarkness.jpg'), clickable: true },
  { id: '96', name: 'Darkness Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/DarknessElemental.jpg'), clickable: true },
  { id: '97', name: 'Master Of Heat', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfHeat.jpg'), clickable: true },
  { id: '98', name: 'Heat Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/HeatElemental.jpg'), clickable: true },
  { id: '99', name: 'Heat Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/HeatElemental2.jpg'), clickable: true },
  { id: '100', name: 'Heat Elemental 3', screen: '', image: require('../../assets/Armor/ElementalArmor/HeatElemental3.jpg'), clickable: true },
  { id: '101', name: 'Master Of Quake', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfQuake.jpg'), clickable: true },
  { id: '102', name: 'Quake Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/QuakeElemental.jpg'), clickable: true },
  { id: '103', name: 'Quake Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/QuakeElemental2.jpg'), clickable: true },
  { id: '104', name: 'Master Of Fusion', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfFusion.jpg'), clickable: true },
  { id: '105', name: 'Fusion Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/FusionElemental.jpg'), clickable: true },
  { id: '106', name: 'Master Of Technology', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfTechnology.jpg'), clickable: true },
  { id: '107', name: 'Technology Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/TechnologyElemental.jpg'), clickable: true },
  { id: '108', name: 'Lava Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/LavaElemental.jpg'), clickable: true },
  { id: '109', name: 'Lava Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/LavaElemental2.jpg'), clickable: true },
  { id: '110', name: 'Lava Elemental 4', screen: '', image: require('../../assets/Armor/ElementalArmor/LavaElemental4.jpg'), clickable: true },
  { id: '111', name: 'Life Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/LifeElemental.jpg'), clickable: true },
  { id: '112', name: 'Life Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/LifeElemental2.jpg'), clickable: true },
  { id: '113', name: 'Master Of Chaos', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfChaos.jpg'), clickable: true },
  { id: '114', name: 'Chaos Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/ChaosElemental.jpg'), clickable: true },
  { id: '115', name: 'Master Of Focus', screen: '', image: require('../../assets/Armor/ElementalArmor/MasterOfFocus.jpg'), clickable: true },
  { id: '116', name: 'Focus Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/FocusElemental.jpg'), clickable: true },
  { id: '117', name: 'Fertility Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/FertilityElemental.jpg'), clickable: true },
  { id: '118', name: 'Fertility Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/FertilityElemental2.jpg'), clickable: true },
  { id: '119', name: 'First Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/FirstElemental.jpg'), clickable: true },
  { id: '120', name: 'First Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/FirstElemental2.jpg'), clickable: true },
  { id: '121', name: 'Love Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/LoveElemental.jpg'), clickable: true },
  { id: '122', name: 'Love Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/LoveElemental2.jpg'), clickable: true },
  { id: '123', name: 'BlackHole Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/BlackHoleElemental.jpg'), clickable: true },
  { id: '124', name: 'BlackHole Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/BlackHoleElemental2.jpg'), clickable: true },
  { id: '125', name: 'BlackHole Elemental 3', screen: '', image: require('../../assets/Armor/ElementalArmor/BlackHoleElemental3.jpg'), clickable: true },
  { id: '126', name: 'BlackHole Elemental 4', screen: '', image: require('../../assets/Armor/ElementalArmor/BlackHoleElemental4.jpg'), clickable: true },
  { id: '127', name: 'BlackHole Elemental 5', screen: '', image: require('../../assets/Armor/ElementalArmor/BlackHoleElemental5.jpg'), clickable: true },
  { id: '128', name: 'BlackHole Elemental 6', screen: '', image: require('../../assets/Armor/ElementalArmor/BlackHoleElemental6.jpg'), clickable: true },
  { id: '129', name: 'BlackHole Elemental 7', screen: '', image: require('../../assets/Armor/ElementalArmor/BlackHoleElemental7.jpg'), clickable: true },
  { id: '130', name: 'Brown Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/BrownElemental.jpg'), clickable: true },
  { id: '131', name: 'Brown Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/BrownElemental2.jpg'), clickable: true },
  { id: '132', name: 'Cosmos Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/CosmosElemental.jpg'), clickable: true },
  { id: '133', name: 'Cosmos Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/CosmosElemental2.jpg'), clickable: true },
  { id: '134', name: 'DarkEnergey Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/DarkEnergeyElemental.jpg'), clickable: true },
  { id: '135', name: 'DarkEnergey Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/DarkEnergeyElemental2.jpg'), clickable: true },
  { id: '136', name: 'DarkMatter Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/DarkMatterELemental.jpg'), clickable: true },
  { id: '137', name: 'DarkMatter Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/DarkMatterElemental2.jpg'), clickable: true },
  { id: '138', name: 'Death Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/DeathElemental.jpg'), clickable: true },
  { id: '139', name: 'Death Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/DeathElemental2.jpg'), clickable: true },
  { id: '140', name: 'Galaxy Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/GalaxyElemental.jpg'), clickable: true },
  { id: '141', name: 'Galaxy Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/GalaxyElemental2.jpg'), clickable: true },
  { id: '142', name: 'IMG 0474 Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/IMG_0474.jpg'), clickable: true },
  { id: '143', name: 'IMG 0475 Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/IMG_0475.jpg'), clickable: true },
  { id: '144', name: 'Maw Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/MawElemental.jpg'), clickable: true },
  { id: '145', name: 'Maw Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/MawElemental2.jpg'), clickable: true },
  { id: '146', name: 'Maw Elemental 3', screen: '', image: require('../../assets/Armor/ElementalArmor/MawElemental3.jpg'), clickable: true },
  { id: '147', name: 'Maw Elemental 4', screen: '', image: require('../../assets/Armor/ElementalArmor/MawElemental4.jpg'), clickable: true },
  { id: '148', name: 'Plasma Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/PlasmaElemental.jpg'), clickable: true },
  { id: '149', name: 'Plasma Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/PlasmaElemental2.jpg'), clickable: true },
  { id: '150', name: 'Plasma Elemental 3', screen: '', image: require('../../assets/Armor/ElementalArmor/PlasmaElemental3.jpg'), clickable: true },
  { id: '151', name: 'Portal Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/PortalElemental.jpg'), clickable: true },
  { id: '152', name: 'Portal Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/PortalElemental2.jpg'), clickable: true },
  { id: '153', name: 'Quantum Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/QuantumElemental.jpg'), clickable: true },
  { id: '154', name: 'Quantum Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/QuantumElemental2.jpg'), clickable: true },
  { id: '155', name: 'Quasar Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/QuasarElemetal.jpg'), clickable: true },
  { id: '156', name: 'Quasar Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/QuasarElemetal2.jpg'), clickable: true },
  { id: '157', name: 'Reality Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/RealityElemental.jpg'), clickable: true },
  { id: '158', name: 'Reality Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/RealityElemental2.jpg'), clickable: true },
  { id: '159', name: 'Stories Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/StoriesElemental.jpg'), clickable: true },
  { id: '160', name: 'Stories Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/StoriesElemental2.jpg'), clickable: true },
  { id: '161', name: 'Rift Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/RiftElemental.jpg'), clickable: true },
  { id: '162', name: 'Rift Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/RiftElemental2.jpg'), clickable: true },
  { id: '163', name: 'Soul Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/SoulElemental.jpg'), clickable: true },
  { id: '164', name: 'Soul Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/SoulElemental2.jpg'), clickable: true },
  { id: '165', name: 'Spinjitzu Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/SpinjitzuElemental.jpg'), clickable: true },
  { id: '166', name: 'Spinjitzu Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/SpinjitzuElemental2.jpg'), clickable: true },
  { id: '167', name: 'Star Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/StarElemental.jpg'), clickable: true },
  { id: '168', name: 'Star Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/StarElemental2.jpg'), clickable: true },
  { id: '169', name: 'Storm Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/StormElemental.jpg'), clickable: true },
  { id: '170', name: 'Storm Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/StormElemental2.jpg'), clickable: true },
  { id: '171', name: 'Telekinisis Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/TelekinisisElemental.jpg'), clickable: true },
  { id: '172', name: 'Telekinisis Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/TelekinisisElemental2.jpg'), clickable: true },
  { id: '173', name: 'Thunder Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/ThunderElemental.jpg'), clickable: true },
  { id: '174', name: 'Thunder Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/ThunderElemental2.jpg'), clickable: true },
  { id: '175', name: 'Void Elemental', screen: '', image: require('../../assets/Armor/ElementalArmor/VoidElemental.jpg'), clickable: true },
  { id: '176', name: 'Void Elemental 2', screen: '', image: require('../../assets/Armor/ElementalArmor/VoidElemental2.jpg'), clickable: true },
  { id: '177', name: 'Void Elemental 3', screen: '', image: require('../../assets/Armor/ElementalArmor/VoidElemental3.jpg'), clickable: true },
  { id: '178', name: 'Void Elemental 4', screen: '', image: require('../../assets/Armor/ElementalArmor/VoidElemental4.jpg'), clickable: true },
].concat([...Array(100).keys()].map(i => ({ id: `${i + 101}`, name: `Elemental ${i + 1}`, screen: '', image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: true })));

export default Elementals;