const Guardians = [
  { id: '1', name: 'Ranger', screen: '', image: require('../../assets/Armor/LoneRanger.jpg'), clickable: true },
  { id: '2', name: 'Lloyd', screen: '', image: require('../../assets/Armor/Lloyd.jpg'), clickable: true },
  { id: '3', name: 'Kai', screen: '', image: require('../../assets/Armor/Kai.jpg'), clickable: true },
  { id: '4', name: 'Cole', screen: '', image: require('../../assets/Armor/Cole.jpg'), clickable: true },
  { id: '5', name: 'Jay', screen: '', image: require('../../assets/Armor/Jay.jpg'), clickable: true },
  { id: '6', name: 'Nya', screen: '', image: require('../../assets/Armor/Nya.jpg'), clickable: true },
  { id: '7', name: 'Zane', screen: '', image: require('../../assets/Armor/Zane.jpg'), clickable: true },
  { id: '8', name: 'Pixal', screen: '', image: require('../../assets/Armor/Pixal.jpg'), clickable: true },
  { id: '9', name: 'Superman', screen: '', image: require('../../assets/Armor/Superman7.jpg'), clickable: true },
  { id: '10', name: 'Batman', screen: '', image: require('../../assets/Armor/Batman.jpg'), clickable: true },
  { id: '11', name: 'Flash', screen: '', image: require('../../assets/Armor/Flash2.jpg'), clickable: true },
  { id: '12', name: 'Green Lantern', screen: '', image: require('../../assets/Armor/GreenLantern.jpg'), clickable: true },
  { id: '13', name: 'Green Ninja', screen: '', image: require('../../assets/Armor/GreenNinja.jpg'), clickable: true },
  { id: '14', name: 'Red Ninja', screen: '', image: require('../../assets/Armor/RedNinja.jpg'), clickable: true },
  { id: '15', name: 'Blue Ninja', screen: '', image: require('../../assets/Armor/BlueNinja.jpg'), clickable: true },
  { id: '16', name: 'Water Ninja', screen: '', image: require('../../assets/Armor/WaterNinja.jpg'), clickable: true },
  { id: '17', name: 'Black Ninja', screen: '', image: require('../../assets/Armor/BlackNinja.jpg'), clickable: true },
  { id: '18', name: 'White Ninja', screen: '', image: require('../../assets/Armor/WhiteNinja.jpg'), clickable: true },
  { id: '19', name: 'Green Lantern 2', screen: '', image: require('../../assets/Armor/GreenLantern2.jpg'), clickable: true },
  { id: '20', name: 'Unnamed', screen: '', image: require('../../assets/Armor/Batman2.jpg'), clickable: true },
  { id: '21', name: 'Unnamed', screen: '', image: require('../../assets/Armor/Superman5.jpg'), clickable: true },
  { id: '22', name: 'Unnamed', screen: '', image: require('../../assets/Armor/Flash.jpg'), clickable: true },
  { id: '23', name: 'Ironman', screen: '', image: require('../../assets/Armor/Ironman.jpg'), clickable: true },
  { id: '24', name: 'Unnamed', screen: '', image: require('../../assets/Armor/Superman6.jpg'), clickable: true },
  { id: '25', name: 'Rogue', screen: '', image: require('../../assets/Armor/Rogue.jpg'), clickable: true },
  { id: '26', name: 'Ronan', screen: '', image: require('../../assets/Armor/Ronan.jpg'), clickable: true },
  { id: '27', name: 'Apocolie', screen: '', image: require('../../assets/Armor/Apocolie.jpg'), clickable: true },
  { id: '28', name: 'Socialation', screen: '', image: require('../../assets/Armor/Jaden.jpg'), clickable: true },
  { id: '29', name: 'Spiltz', screen: '', image: require('../../assets/Armor/Jonas.jpg'), clickable: true },
  { id: '30', name: 'Voice Fry', codename: 'Voice Fry', screen: '', clickable: true, image: require('../../assets/Armor/Johnathon_cleanup.jpg') },
];

export default Guardians;