const Guardians = [
  { name: 'Ranger', screen: '', image: require('../../assets/Armor/LoneRanger.jpg'), clickable: true },
  { name: 'Superman', screen: '', image: require('../../assets/Armor/Superman7.jpg'), clickable: true },
  { name: 'Batman', screen: '', image: require('../../assets/Armor/Batman.jpg'), clickable: true },
  { name: 'Flash', screen: '', image: require('../../assets/Armor/Flash2.jpg'), clickable: true },
  { name: 'Green Lantern', screen: '', image: require('../../assets/Armor/GreenLantern.jpg'), clickable: true },
  { name: 'Green Lantern 2', screen: '', image: require('../../assets/Armor/GreenLantern2.jpg'), clickable: true },
  { name: 'Lloyd', screen: '', image: require('../../assets/Armor/Lloyd.jpg'), clickable: true },
  { name: 'Kai', screen: '', image: require('../../assets/Armor/Kai.jpg'), clickable: true },
  { name: 'Cole', screen: '', image: require('../../assets/Armor/Cole.jpg'), clickable: true },
  { name: 'Jay', screen: '', image: require('../../assets/Armor/Jay.jpg'), clickable: true },
  { name: 'Nya', screen: '', image: require('../../assets/Armor/Nya.jpg'), clickable: true },
  { name: 'Zane', screen: '', image: require('../../assets/Armor/Zane.jpg'), clickable: true },
  { name: 'Pixal', screen: '', image: require('../../assets/Armor/Pixal.jpg'), clickable: true },
  { name: 'Unnamed', screen: '', image: require('../../assets/Armor/Flash.jpg'), clickable: true },
  { name: 'Unnamed', screen: '', image: require('../../assets/Armor/Superman5.jpg'), clickable: true },
  { name: 'Rogue', screen: '', image: require('../../assets/Armor/Rogue.jpg'), clickable: true },
  { name: 'Ronan', screen: '', image: require('../../assets/Armor/Ronan.jpg'), clickable: true },
  { name: 'Apocolie', screen: '', image: require('../../assets/Armor/Apocolie.jpg'), clickable: true },
  { name: 'Unnamed', screen: '', image: require('../../assets/Armor/Batman2.jpg'), clickable: true },
  { name: 'Green Ninja', screen: '', image: require('../../assets/Armor/GreenNinja.jpg'), clickable: true },
  { name: 'Red Ninja', screen: '', image: require('../../assets/Armor/RedNinja.jpg'), clickable: true },
  { name: 'Blue Ninja', screen: '', image: require('../../assets/Armor/BlueNinja.jpg'), clickable: true },
  { name: 'Water Ninja', screen: '', image: require('../../assets/Armor/WaterNinja.jpg'), clickable: true },
  { name: 'Black Ninja', screen: '', image: require('../../assets/Armor/BlackNinja.jpg'), clickable: true },
  { name: 'White Ninja', screen: '', image: require('../../assets/Armor/WhiteNinja.jpg'), clickable: true },
  { name: 'Unnamed', screen: '', image: require('../../assets/Armor/Superman6.jpg'), clickable: true },
  { name: 'Ironman', screen: '', image: require('../../assets/Armor/Ironman.jpg'), clickable: true },
  { name: 'Socialation', screen: '', image: require('../../assets/Armor/Jaden.jpg'), clickable: true },
  { name: 'Spiltz', screen: '', image: require('../../assets/Armor/Jonas.jpg'), clickable: true },
  { name: 'Voice Fry', codename: 'Voice Fry', screen: '', clickable: true, image: require('../../assets/Armor/Johnathon_cleanup.jpg') },
];

export default Guardians;