// JusticeDescription.js
// A sacred record of heroes who defend realms — their power, their valor, their eternal watch.

export const descriptions = {
  // GUARDIANS
//   'Ranger': 'The lone sentinel of the wilds, swift and unyielding in the face of shadows.',
//   'Superman': 'The Man of Steel — beacon of hope, unbreakable will, defender of the innocent.',
//   'Batman': 'The Dark Knight — master of shadows, intellect forged in tragedy, eternal vigilante.',
//   'Flash': 'The Scarlet Speedster — blur of justice, racing against time to save all.',
//   'Green Lantern': 'Wielder of the emerald will — forging light from courage, guardian of sectors.',
//   'Green Lantern 2': 'Second bearer of the ring — unyielding resolve, illuminating the darkest voids.',
//   'Lloyd': 'The Green Ninja — master of energy, leader born from prophecy and balance.',
//   'Kai': 'The Red Ninja — fire incarnate, fierce warrior with a heart of flames.',
//   'Cole': 'The Black Ninja — earth\'s unmovable force, strength rooted in loyalty.',
//   'Jay': 'The Blue Ninja — lightning\'s quick wit, inventor and stormbringer.',
//   'Nya': 'The Water Ninja — fluid grace, tidal power shaping destiny.',
//   'Zane': 'The White Ninja — ice-cold precision, nindroid of logic and hidden emotion.',
//   'Pixal': 'The digital ally — code-made companion, evolving beyond circuits.',
//   'Unnamed': 'Mystery guardian — veiled in enigma, power unspoken yet profound.',
//   'Rogue': 'The rebel force — untamed energy, defying odds with cunning and might.',
//   'Ronan': 'The cosmic enforcer — hammer of judgment, wandering star of retribution.',
//   'Apocolie': 'The apocalyptic harbinger — chaos embodied, reshaping worlds in ruin.',
//   'Green Ninja': 'Ultimate balance — harmony of elements, prophecy fulfilled.',
//   'Red Ninja': 'Blazing fury — flames of protection, unquenchable spirit.',
//   'Blue Ninja': 'Electric surge — bolts of innovation, shocking the unjust.',
//   'Water Ninja': 'Tidal guardian — waves of resilience, flowing through adversity.',
//   'Black Ninja': 'Rock-solid defender — mountains of strength, unshakable foundation.',
//   'White Ninja': 'Frozen tactician — glaciers of strategy, chilling precision.',
//   'Ironman': 'The armored genius — tech-forged hero, billionaire philanthropist playboy.',

//   // ELEMENTALS
//   'Dragonie': 'Primordial dragon essence — fire and flight, ancient guardian of realms.',
//   'Source Mother': 'The origin of all — nurturing force, birthing elements from void.',
//   'First Elemental Master': 'Pioneer of power — weaver of the first threads of elemental might.',
//   'Master Of Creation': 'Builder of worlds — shaping reality from thought and will.',
//   'Creation Elemental': 'Essence of genesis — birthing form from nothingness.',
//   'Creation Elemental 2': 'Variant of birth — evolving creation with endless potential.',
//   'Creation Elemental 3': 'Advanced creator — refining existence with divine touch.',
//   'GoldenPower Elemental Master': 'Lord of aurum — radiant energy, unbreakable golden force.',
//   'GoldenPower Elemental': 'Golden surge — illuminating paths with pure, invincible light.',
//   'Master Of Destruction': 'Harbinger of end — shattering bonds, remaking through ruin.',
//   'Destruction Elemental': 'Force of unraveling — chaos that clears the way for renewal.',
//   'Destruction Elemental 2': 'Evolved destroyer — precision in demolition, targeted entropy.',
//   'Destruction Elemental 3': 'Ultimate breaker — crumbling empires with a whisper.',
//   'DragonPower Elemental': 'Draconic might — scales of power, breath of ancient fury.',
//   'DragonPower Elemental 2': 'Enhanced dragon — wings of dominion, claws of conquest.',
//   'OniPower Elemental': 'Demonic shadow — masks of terror, corrupting influence.',
//   'OniPower Elemental 2': 'Deeper oni — horns of deception, eternal night bringer.',
//   'Master Of Fire': 'Lord of inferno — flames that forge and consume.',
//   'Fire Elemental': 'Blazing spirit — heat of passion, purifying blaze.',
//   'Master Of Lightning': 'Storm sovereign — bolts that electrify and empower.',
//   'Lightning Elemental': 'Electric essence — surges of speed, shocking revelations.',
//   'Master Of Ice': 'Frost emperor — chill that preserves and petrifies.',
//   'Ice Elemental': 'Glacial force — frozen eternity, unyielding cold.',
//   'Ice Elemental 2': 'Deeper freeze — shards of winter, crystalline defense.',
//   'Ice Elemental 3': 'Absolute zero — halting time in icy embrace.',
//   'Master Of Earth': 'Titan of terrain — quakes that reshape landscapes.',
//   'Earth Elemental': 'Stone guardian — bedrock stability, mountainous might.',
//   'Master Of Water': 'Ocean overlord — tides that heal and overwhelm.',
//   'Water Elemental': 'Fluid form — waves of adaptability, drowning despair.',
//   'Master Of Energy': 'Core of vitality — pulses that invigorate and destroy.',
//   'Energy Elemental': 'Radiant pulse — life force amplified, boundless vigor.',
//   'Energy Elemental 2': 'Amplified energy — surges of pure potential.',
//   'Energy Elemental 3': 'Overcharged essence — exploding with raw power.',
//   'Energy Elemental 4': 'Ultimate conduit — channeling infinity.',
//   'Master Of Wind': 'Gale governor — breezes that carry secrets and storms.',
//   'Wind Elemental': 'Aerial spirit — whispers of freedom, hurricanes of change.',
//   'Master Of Shadow': 'Umbra lord — darkness that conceals and consumes.',
//   'Shadow Elemental': 'Void walker — eclipses of fear, silent assassin.',
//   'Master Of Light': 'Luminary leader — beams that reveal and purify.',
//   'Light Elemental': 'Radiant being — dawn\'s promise, banishing night.',
//   'Light Elemental 2': 'Brighter glow — prisms of truth, healing rays.',
//   'Light Elemental 3': 'Divine illumination — stars aligned in holy fire.',
//   'Master Of Metal': 'Forge king — alloys of endurance, unbendable will.',
//   'Metal Elemental': 'Steel soul — forged in trials, rustproof resolve.',
//   'Master Of Poison': 'Venom viceroy — toxins that corrupt and cure.',
//   'Poison Elemental': 'Toxic essence — serpentine strike, lingering decay.',
//   'Master Of Nature': 'Verdant visionary — growth that entangles and enlivens.',
//   'Nature Elemental': 'Green guardian — vines of life, thorns of protection.',
//   'Master Of Mind': 'Psionic sovereign — thoughts that bend reality.',
//   'Mind Elemental': 'Cerebral force — illusions of control, telepathic ties.',
//   'Brown Elemental': 'Earthen variant — mud and mire, grounding presence.',
//   'Brown Elemental 2': 'Deeper soil — fertile chaos, nurturing decay.',
//   'Cosmos Elemental': 'Stellar being — galaxies in motion, cosmic harmony.',
//   'Cosmos Elemental 2': 'Universal force — nebulae of creation, black holes of end.',
//   'Singularity Elemental': 'Point of no return — gravity\'s pull, infinite density.',
//   'Singularity Elemental 2': 'Event horizon — warping space, devouring light.',
//   'DarkMatter Elemental': 'Invisible mass — unseen influence, binding the void.',
//   'DarkMatter Elemental 2': 'Shadow gravity — hidden forces shaping fate.',
//   'Death Elemental': 'Reaper\'s touch — end of cycles, harvest of souls.',
//   'Death Elemental 2': 'Eternal rest — scythe of closure, peaceful oblivion.',
//   'Galaxy Elemental': 'Spiral sovereign — arms of stars, whirlpools of wonder.',
//   'Galaxy Elemental 2': 'Cosmic cluster — billions of lights, unified dance.',
//   'Healing Elemental': 'Restorative ray — mending wounds, reviving spirits.',
//   'Healing Elemental 2': 'Life\'s balm — soothing auras, regenerative glow.',
//   'Maw Elemental': 'Abyssal hunger — jaws of the deep, consuming all.',
//   'Maw Elemental 2': 'Voracious void — teeth of eternity, endless appetite.',
//   'Maw Elemental 3': 'Gaping chasm — swallowing worlds, unquenchable thirst.',
//   'Maw Elemental 4': 'Bottomless pit — devouring darkness, infinite gorge.',
//   'Plasma Elemental': 'Superheated state — ions of fury, electrified blaze.',
//   'Plasma Elemental 2': 'Solar flare — bursts of energy, stellar eruptions.',
//   'Plasma Elemental 3': 'Fusion force — nuclear heart, radiant destruction.',
//   'Portal Elemental': 'Gateway guardian — doors to dimensions, bridges between.',
//   'Portal Elemental 2': 'Warp weaver — rifts in reality, shortcuts through space.',
//   'Quantum Elemental': 'Particle prince — probabilities in flux, entangled fates.',
//   'Quantum Elemental 2': 'Wave function — collapsing possibilities, uncertain power.',
//   'Quasar Elemental': 'Blazing beacon — jets of light, cosmic lighthouses.',
//   'Quasar Elemental 2': 'Radiant core — supermassive shine, blinding intensity.',
//   'Reality Elemental': 'Fabric forger — bending existence, rewriting rules.',
//   'Reality Elemental 2': 'Illusion master — shifting truths, dreammade real.',
//   'Stories Elemental': 'Narrative nexus — tales that shape, legends alive.',
//   'Stories Elemental 2': 'Myth weaver — epics unfolding, heroes born anew.',
//   'Rift Elemental': 'Tear in time — fractures of fate, chaotic crossings.',
//   'Rift Elemental 2': 'Dimensional divide — portals of peril, unstable gates.',
//   'Soul Elemental': 'Ethereal essence — spirits unbound, inner light eternal.',
//   'Soul Elemental 2': 'Astral anchor — binding life, transcending flesh.',
//   'Spinjitzu Elemental': 'Tornado of elements — spinning balance, ninja art supreme.',
//   'Spinjitzu Elemental 2': 'Whirlwind warrior — cycles of power, harmonious fury.',
//   'DarkEnergy Elemental': 'Cosmic accelerator — expanding voids, unseen propulsion.',
//   'DarkEnergy Elemental 2': 'Repulsive force — pushing boundaries, infinite expansion.',
//   'Storm Elemental': 'Tempest tamer — thunder and rain, nature\'s rage unleashed.',
//   'Storm Elemental 2': 'Cyclonic fury — winds of change, lightning\'s wrath.',
//   'Telekinisis Elemental': 'Mind mover — lifting with thought, invisible hands.',
//   'Telekinisis Elemental 2': 'Psychic push — bending matter, mental mastery.',
//   'Thunder Elemental': 'Booming voice — echoes of power, deafening strikes.',
//   'Thunder Elemental 2': 'Resonant roar — vibrations of might, shattering silence.',
//   'Void Elemental': 'Empty abyss — absence of all, swallowing existence.',
//   'Void Elemental 2': 'Null zone — erasing presence, silent vacuum.',
//   'Void and Shadow Elemental': 'Merged darkness — voids and shades, ultimate obscurity.',
//   'Void and Shadow Elemental 2': 'Eclipse eternal — blending nothing with night.',

//   // JUSTICE LEAGUE
//   'Starman': 'Cosmic crusader — stars as allies, light against dark.',
//   'Dragoknight': 'Dragon-forged knight — scales and sword, mythical might.',
//   'Flare': 'Fiery avenger — blazes of justice, burning bright.',
//   'Vindra': 'Wind whisperer — gusts of speed, invisible vengeance.',
//   '': 'Unnamed sentinel — silent protector, deeds over names.', // For IMG1-5

//   // THE SEVEN (OMNI JUMPERS)
//   'The Voyager': 'Realm traverser — jumping through worlds, endless exploration.',
//   'The Foundation': 'Bedrock of unity — stabilizing chaos, unshakeable core.',
//   'The Origin': 'Prime source — beginning of power, eternal genesis.',
//   'The Scientist': 'Innovation incarnate — experiments that redefine limits.',
//   'The Visitor': 'Interdimensional guest — insights from beyond, alien wisdom.',
//   'The Imagined': 'Dream shaper — fantasies made flesh, impossible realized.',
//   'The Order': 'Balance enforcer — harmony in turmoil, structured peace.',
//   'The Paradigm': 'Rule breaker — shifting paradigms, new eras born.',
};

export default descriptions;