export const descriptions = {
  'Angela': 'Celestial Angel, adorned in radiant, winged armor, channels divine energy to inspire and protect her allies with unwavering grace.',
  'Todd': 'Stellar, clad in cosmic-infused armor, wields starlight to illuminate paths and bolster defenses with celestial strength.',
  'Molly': 'Teddy Bear, with warm, comforting armor, uses her nurturing spirit to heal and uplift, a beacon of hope in battle.',
  'Mary': 'Auric, draped in golden armor, commands an aura of leadership, weaving protective fields with her radiant presence.',
  'Chance': 'Crimson Crown, in regal, red-hued armor, leads with courage, his strikes imbued with royal authority and precision.',
  'Ava': 'Prismatic Pulse, wearing vibrant, multicolored armor, manipulates light to dazzle foes and enhance team synergy.',
  'Charlie': 'Iron Olympian, encased in unyielding steel, embodies raw power and resilience, standing as a bulwark against any threat.',
  'Lumi': 'Fade Shade, in shadowy, ethereal armor, moves unseen, striking with precision and disrupting enemy plans.',
  'Heather S': 'Verdant, cloaked in nature-inspired armor, harnesses the power of the earth to heal allies and control the battlefield.',
  'Bobby': 'Crown Medic, a military doctor in tactical armor, combines medical expertise with combat prowess to save lives under fire.',
  'Liberty': 'Serenity, in tranquil, flowing armor, radiates calm and healing energy, soothing allies and dispelling chaos.',
  'Ammon': 'Valoron, in shining, valorous armor, inspires courage, leading charges with unbreakable resolve and strategic brilliance.',
  'Piper': 'Jetstrike, in sleek, aerodynamic armor, moves with lightning speed, delivering swift, devastating attacks.',
  'Gemma': 'Slendowg, with agile, streamlined armor, uses her quick wit and reflexes to outmaneuver opponents with ease.',
  'Savannah': 'Vivid Spark, in electrified armor, channels bursts of energy to stun foes and energize her team.',
  'Lee': 'Codeforge, in tech-enhanced armor, manipulates digital systems to hack defenses and support allies with precision.',
  'Emilee': 'Luminous Aria, in melodic, glowing armor, uses harmonic vibrations to soothe allies and disrupt enemies.',
  'Samantha': 'Velocity Vibe, in dynamic, streamlined armor, moves at blinding speeds, striking with rhythmic precision.',
  'Ella': 'Aerial Serenade, with winged, flowing armor, dances through the air, weaving enchantments to bolster her team.',
  'Annie': 'Sage Mentor, a teacher in wise, ornate armor, imparts knowledge and strategy, guiding her team to victory.',
  'Paul': 'Iron Law, a police officer in fortified armor, upholds justice with unyielding strength and tactical expertise.',
  'McKinley': 'Rebuncious, in bold, rebellious armor, charges into battle with fearless energy and disruptive force.',
  'Whitney': 'Veilweaver, in mystic, veiled armor, manipulates illusions to confuse foes and protect her allies.',
  'Vinson': 'Ironchad, in heavy, fortified armor, stands as an immovable defender, absorbing and redirecting enemy attacks.',
  'Wesley': 'Steelframe, a bodybuilder in massive, steel-clad armor, uses brute strength to dominate the battlefield.',
  'Melissa': 'Auric Skyweaver, in golden, celestial armor, weaves protective skies, shielding allies with radiant energy.',
  'Jackson': 'Rhythmic Flux, a dancer in fluid, dynamic armor, moves with grace, disorienting foes with rhythmic strikes.',
  'Mason': 'Fortress King, in towering, regal armor, commands the battlefield with strategic might and unyielding defense.',
  'Rylie': 'Star Gleam, in sparkling, starry armor, radiates light to inspire and guide her team through darkness.',
  'Sammy': 'Swift Pack, in agile, pack-inspired armor, moves with coordinated speed, striking with relentless energy.',
  'David': 'Ironforge, in rugged, forged armor, crafts unbreakable defenses and delivers powerful, hammering blows.',
  'Isaydy': 'Mist Haven, in misty, elusive armor, creates safe havens with fog, shielding allies and ambushing foes.',
  'Darron': 'Crag Rock, in stone-like, durable armor, stands as a mountain, grounding his team with steadfast resilience.',
  'Isabel': 'Breezestrom, in airy, tempestuous armor, unleashes gusts of wind to control the battlefield and protect her allies.',
  'Gary jr': 'Legacy Shield, in ancestral, fortified armor, carries his family’s honor, protecting with unyielding loyalty.',
  'Sarah': 'Hope, in radiant, uplifting armor, inspires her team with boundless optimism and restorative energy.',
  'Josh': 'Defention, in solid, defensive armor, holds the line with unbreakable resolve and tactical precision.',
  'Garden': 'Pharoll, in nature-infused armor, channels ancient growth to heal and strengthen the battlefield.',
  'Sophia': 'Chroma Sprint, in vibrant, agile armor, dashes with colorful energy, striking with unpredictable flair.',
  'Paisley': 'Prism Weaver, in prismatic, intricate armor, crafts light-based defenses and dazzling attacks.',
  'Ellie': 'Ethereal Flutter, in delicate, ethereal armor, moves with grace, healing allies with gentle, mystical touches.',
  'Jennifer': 'Eternal Guardian, in ornate, timeless armor, stands as a protector, guiding her team with wisdom and strength.',
  'Sean': 'Vanguard, in bold, frontline armor, leads charges with fearless determination and tactical prowess.',
  'Heather C': 'Sylvara, in woodland-inspired armor, weaves nature’s magic to heal and control the environment.',
  'Brett small': 'Aegis, in shielded, protective armor, stands as a guardian, deflecting attacks with unmatched resilience.',
  'Jake': 'Nova Sentinel, in radiant, futuristic armor, guards with explosive energy and unwavering vigilance.',
  'Ailey': 'Chromatic Blaze, in vibrant, fiery armor, unleashes colorful flames to overwhelm foes and inspire allies.',
  'Aubrey': 'Seraphine Dawn, in angelic, dawn-lit armor, brings hope and healing with radiant, uplifting energy.',
  'James': 'Dreadforge, in heavy, dark armor, forges fear into strength, dominating with relentless combat prowess.',
  'Ryan': 'Managerial, in strategic, commanding armor, leads with calculated precision and unyielding authority.',
  'Maren': 'Luminary Veil, in glowing, veiled armor, protects with radiant barriers and mystic insight.',
  'Sasha': 'Codex, in scholarly, tech-infused armor, decodes enemy strategies and enhances team coordination.',
  'Ian': 'Sparous, in fiery, agile armor, strikes with sparking intensity and relentless energy.',
  'Riker': 'Ironstrike, in metallic, precise armor, delivers devastating blows with unerring accuracy.',
  'Dakota': 'Shadow Cipher, in dark, cryptic armor, operates in secrecy, unraveling enemy plans with stealth.',
  'Lora': 'Roseheart, in floral, compassionate armor, heals and inspires with a nurturing, loving presence.',
  'Wayne': 'Sovereign, in regal, commanding armor, rules the battlefield with authority and strategic mastery.',
  'Elizabeth': 'Harmony Warden, in balanced, serene armor, restores peace and strengthens allies with calm resolve.',
  'Christopher': 'Steel, in unyielding, metallic armor, stands as a pillar of strength and endurance.',
  'Tom': 'Stormforge, a Special Forces Marine in tactical armor, unleashes surging combat with unyielding protection.',
  'Brett': 'Doctoral, in scholarly, fortified armor, combines intellect and resilience to support and defend.',
  'Angie': 'Ethereal Guardian, in mystical, protective armor, shields allies with otherworldly grace and power.',
  'Bryce': 'Moesek, in rugged, versatile armor, adapts to any challenge with relentless determination.',
  'Lillie': 'Slick Blade, in sleek, sharp armor, strikes with precision and agility, cutting through opposition.',
  'Addie': 'Prism Voyager, in vibrant, exploratory armor, navigates battles with colorful, adventurous energy.',
  'Purdy': 'Old Faithful, in classic, dependable armor, provides steadfast support and unwavering loyalty.',
  'Matt': '[redacted], in mysterious, obscured armor, operates in secrecy with unmatched strategic prowess.',
  'Jessica': 'CareTechnial, in nurturing, tech-enhanced armor, heals and supports with precision and care.',
  'Kyle': 'Shadowcore, in dark, fortified armor, controls the battlefield with stealth and unyielding strength.',
  'Daisy': 'Floral, in vibrant, flower-inspired armor, blooms with healing energy and natural resilience.',
  'Rose': 'Prism, in radiant, prismatic armor, refracts light to dazzle foes and protect allies.',
  'Mikie': 'Steelth, in stealthy, metallic armor, combines strength and subtlety for covert strikes.',
  'Prairie': 'Flowertwister, in swirling, floral armor, manipulates nature’s winds to control and defend.',
  'Ryan kid': 'Ven-noir, in dark, venomous armor, strikes with youthful energy and shadowy precision.',
  'Liam': 'Veteran, in battle-worn, resilient armor, brings experience and strength to every fight.',
  'Chad': 'Codester, in tech-savvy, agile armor, hacks and disrupts with coded precision and speed.',
  'Rochelle': 'White Veil, in pure, veiled armor, protects with radiant purity and mystic barriers.',
  'Annabeth': 'Novanna, in celestial, innovative armor, pioneers new strategies with radiant energy.',
  'Levi': 'StoneWreck, in massive, stone-like armor, crushes opposition with earth-shaking force.',
  'Troy': 'Foreman, in rugged, commanding armor, leads with industrial strength and unyielding resolve.',
  'Gary': 'Entrpatorial, in bold, entrepreneurial armor, drives innovation and leadership in battle.',
  'Jeanine': 'Hearth Matron, in warm, protective armor, nurtures and shields with maternal strength.',
  'Sharrel': 'Airrow, in swift, airy armor, strikes with precision and controls the battlefield with gusts.',
  'Dorthy': 'Star Keeper, in celestial, protective armor, guards her team with starry wisdom and strength.',
  'GMA Parker': 'Eternal Archon, in ornate, vintage armor, heals and guides with timeless wisdom and solace.',
  'Marlyn': 'Sky Weaver, in airy, woven armor, manipulates the skies to protect and empower her allies.',
  'Robert': 'Iron Sentinel, in fortified, vigilant armor, stands as a guardian with unyielding resolve.',
  'Arlene Hendricks': 'Flame Guardian, in fiery, protective armor, shields allies with blazing strength.',
  'Nate Hendricks': 'Wind Striker, in swift, windy armor, delivers rapid, cutting strikes with precision.',
  'Kris': 'Techno Spirit, in futuristic, spirited armor, enhances allies with technological prowess.',
  'Carlo': 'Goldenmind, in golden, intellectual armor, strategizes with brilliant insight and clarity.',
  'Cham Cham Kaleigha': 'Star Vortex, in swirling, cosmic armor, channels stellar energy to overwhelm foes.',
};

export default descriptions;