export const descriptions = {
  // // College
  // 'Mason Erickson': 'Description for Mason Erickson goes here',
  // 'Davis Clark': 'Description for Davis Clark goes here',
  // 'Mckain Bailey': 'Description for Mckain Bailey goes here',

  // // Aileen's Friends
  // 'Kemerey': 'Description for Kemerey goes here',
  // 'Sheryl': 'Description for Sheryl goes here',
  // 'Krystel': 'Description for Krystel goes here',
  // 'Deb': 'Description for Deb goes here',
  // 'Emma BYU': 'Description for Emma BYU goes here',
  // 'Jessica BYU': 'Description for Jessica BYU goes here',
  // 'Victoria': 'Description for Victoria goes here',

  // // Young Womens
  // 'Mika': 'Description for Mika goes here',
  // 'Malia': 'Description for Malia goes here',
  // 'Jami': 'Description for Jami goes here',
  // 'Cami': 'Description for Cami goes here',
  // 'Kanani': 'Description for Kanani goes here',

  // // High School
  // 'Kenndedy Carman': 'Description for Kenndedy Carman goes here',
  // 'Jack Clark': 'Description for Jack Clark goes here',
  // 'Emma Bronson': 'Description for Emma Bronson goes here',
  // 'Ella Duce': 'Description for Ella Duce goes here',
  // 'Addison Morris': 'Description for Addison Morris goes here',
  // 'Cody Cline': 'Description for Cody Cline goes here',
  // 'Alyssa': 'Description for Alyssa goes here',
  // 'Justin Platt': 'Description for Justin Platt goes here',
  // 'Zack Dustin': 'Description for Zack Dustin goes here',
  // 'Josh Clark': 'Description for Josh Clark goes here',
  // 'Jessica Fisher': 'Description for Jessica Fisher goes here',
  // 'Miles Robinson': 'Description for Miles Robinson goes here',
  // 'Lizzy': 'Description for Lizzy goes here',
  // 'Sam': 'Description for Sam goes here',
  // 'Spencer': 'Description for Spencer goes here',
  // 'Dylan': 'Description for Dylan goes here',
  // 'Kinnley Cline': 'Description for Kinnley Cline goes here',
  // 'Sanford Duncan': 'Description for Sanford Duncan goes here',
  // 'Magic Matt': 'Description for Magic Matt goes here',
  // 'Kanyon': 'Description for Kanyon goes here',
  // 'John': 'Description for John goes here',
  // 'Quinton': 'Description for Quinton goes here',
  // 'Emery': 'Description for Emery goes here',
  // 'Mason': 'Description for Mason goes here',
  // 'Xavier': 'Description for Xavier goes here',
  // 'Josh Davis': 'Description for Josh Davis goes here',
  // 'Teagan': 'Description for Teagan goes here',
  // 'Carter': 'Description for Carter goes here',
  // 'Nate Anderson': 'Description for Nate Anderson goes here',

  // // Jr. High
  // 'Paxton': 'Description for Paxton goes here',
  // 'Spencer Hill': 'Description for Spencer Hill goes here',
  // 'Cassidy Cline': 'Description for Cassidy Cline goes here',
  // 'Adam Leger': 'Description for Adam Leger goes here',
  // 'Sam Phillips': 'Description for Sam Phillips goes here',
  // 'Will Knight': 'Description for Will Knight goes here',
  // 'Hayden Perks': 'Description for Hayden Perks goes here',
  // 'Cienna': 'Description for Cienna goes here',
  // 'Clayton': 'Description for Clayton goes here',
  // 'Bridget': 'Description for Bridget goes here',
  // 'Ryan': 'Description for Ryan goes here',
  // 'Carson': 'Description for Carson goes here',
  // 'Sydney': 'Description for Sydney goes here',
  // 'Natalie': 'Description for Natalie goes here',

  // // Elementary
  // 'Josh Noble': 'Description for Josh Noble goes here',
  // 'Matt Lihpia': 'Description for Matt Lihpia goes here',
  // 'Jose Rodriguez': 'Description for Jose Rodriguez goes here',
  // 'Jorge': 'Description for Jorge goes here',
  // 'Tayton Baker': 'Description for Tayton Baker goes here',
  // 'Michael': 'Description for Michael goes here',
  // 'Thomas': 'Description for Thomas goes here',
  // 'Veronica Teaford': 'Description for Veronica Teaford goes here',
  // 'Erica Teaford': 'Description for Erica Teaford goes here',
  // 'Nate Greene': 'Description for Nate Greene goes here',
  // 'Ivan Aparicio': 'Description for Ivan Aparicio goes here',
  // 'Abby': 'Description for Abby goes here',
  // 'Lupa': 'Description for Lupa goes here',
  // 'Shanna': 'Description for Shanna goes here',
  // 'Elizabeth': 'Description for Elizabeth goes here',
  // 'Noah': 'Description for Noah goes here',
  // 'Elise': 'Description for Elise goes here',
  // 'Brigdan': 'Description for Brigdan goes here',
  // 'Addie': 'Description for Addie goes here',

  // // Acquaintances
  // 'Jack Smith': 'Description for Jack Smith goes here',
  // 'Dustin Edmonds': 'Description for Dustin Edmonds goes here',
};

export default descriptions;