// 🎯 Static mapping of character images for Legionaires
const legionImages = {
    'Mason Erickson': require('../../assets/Armor/MasonEPlaceHolder.jpg'),
    'Davis Clark': require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    'Cody Cline': require('../../assets/Armor/CodyPlaceHolder.jpg'),
    'Kinnley Cline': require('../../assets/Armor/KinnleyPlaceHolder.jpg'),
    'Cassidy Cline': require('../../assets/Armor/CassidyPlaceHolder.jpg'),
    'Jack Smith': require('../../assets/Armor/JackPlaceHolder.jpg'),
    Dylan: require('../../assets/Armor/DylanPlaceHolder.jpg'),
    'Jessica Fisher': require('../../assets/Armor/JessicaFPlaceHolder.jpg'),
    'Dustin Edmonds': require('../../assets/Armor/DustinEPlaceHolder.jpg'),
    Justin: require('../../assets/Armor/JustinPlaceHolder2.jpg'),
    Zack: require('../../assets/Armor/ZackPlaceHolder2.jpg'),
    'Josh Noble': require('../../assets/Armor/JoshNoblePlaceHolder.jpg'),
    'Will Knight': require('../../assets/Armor/WillKPlaceHolder.jpg'),
    Christian: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    John: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Jose: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Matt: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Anthony: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Miles: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Cieanna: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Natalie: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Kanyon: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Emily: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Jarom: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Avery: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    'Kennedy Carman': require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Sydney: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    'Hunter': require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    'Cami Webb': require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    'Spencer Hill': require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Clayton: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    'Spencer L': require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    'Malia Holley': require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Mika: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Jason: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Allysa: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Josh: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    'John 1': require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    'John 2': require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Abby: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Tagun: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    'Adam Ledger': require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Sam: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    'Kaden Hanson 1': require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    'Sam Philops': require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    'Carter Olsen': require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    'Issac Philops': require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Hayden: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    'Parker Gold': require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    'Gabe Parker': require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    'Sanford Duncan': require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Lizzy: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Kyle: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Ivan: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Grace: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    'Kaden Hansen 2': require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Kaia: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Erica: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Veronica: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Elizabeth: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Shanna: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Lupa: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Kody: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    'Nate Greene': require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Nick: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Thomas: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Kason: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Bridger: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Addie: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Brigdon: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Noah: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Elsie: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Mason: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    'Emery Clark': require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Xzavier: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Quinton: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    'Quinton C': require('../../assets/Armor/DefaultPlaceHolder.jpg'),
    Quincy: require('../../assets/Armor/DefaultPlaceHolder.jpg'),
  };
  
  export default legionImages;
  