import legionImages from './LegionairesImages';

// 🎯 Legionaires Member List with Categories and Superhero Codenames
export const memberCategories = [
  {
    category: "College",
    members: [
      { name: 'Mason Erickson', codename: 'Might' },
      { name: 'Davis Clark', codename: 'Cyberman' },
    ],
  },
  {
    category: "High School",
    members: [
      { name: 'Kenndedy Carman', codename: '' },
      { name: 'Jack Clark', codename: 'Blaze' },
      { name: 'Emma Bronson', codename: 'Synergy' },
      { name: 'Ella Duce', codename: 'Big Sister' },
      { name: 'Addison Morris', codename: 'Legend' },
      { name: 'Cody Cline', codename: '' },
      { name: 'Justin Platt', codename: '' },
      { name: 'Zack Dustin', codename: '' },
      { name: 'Josh Clark', codename: '' },
      { name: 'Jessica Fisher', codename: 'Aurora' },
      { name: 'Miles Robinson', codename: '' },
      { name: 'Lizzy', codename: '' },
      { name: 'Sam', codename: 'Vortex' },
      { name: 'Spencer', codename: 'Nova' },
      { name: 'Dylan', codename: 'Stormchaser' },
      { name: 'Kinnley Cline', codename: '' },
      { name: 'Sanfor Duncan', codename: 'Thunderbolt' },
      { name: 'Magic Matt', codename: 'Illusionist' },
      { name: 'Emery', codename: 'Mirage' },
      { name: 'Mason', codename: 'Titan' },
      { name: 'Xavier', codename: 'Phantom' },
      { name: 'Josh Davis', codename: '' },
      { name: 'John', codename: '' },
    ],
  },
  {
    category: "Jr. High",
    members: [
      { name: 'Paxton', codename: 'Spark' },
      { name: 'Spencer Hill', codename: 'Lightning Bolt' },
      { name: 'Cassidy Cline', codename: 'Siren' },
      { name: 'Adam Leger', codename: 'Steel Wing' },
      { name: 'Carter Olsen', codename: 'Nightshade' },
      { name: 'Sam Phillips', codename: 'Tempest' },
      { name: 'Will Knight', codename: 'Crusader' },
      { name: 'Hayden Perks', codename: '' },
      { name: 'Cienna', codename: '' },
      { name: 'Clayton', codename: '' },
      { name: 'Natalie', codename: 'Luminara' },
      { name: 'Kanyon', codename: 'Cyclone' },
      { name: 'Steven', codename: 'Obsidian' },
      { name: 'Kaden Hansen', codename: 'Flare' },
      { name: 'Julio', codename: '' },
      { name: 'Jackson', codename: '' },
      { name: 'Kai', codename: '' },
      { name: 'Sami', codename: '' },
      { name: 'Alyssa', codename: '' },
      { name: 'Samuel', codename: '' },
      { name: 'Jonathan', codename: '' },
      { name: 'Adam', codename: '' },
      { name: 'Kendra', codename: '' },
      { name: 'Olivia', codename: '' },
      { name: 'Quinton', codename: '' },
      { name: 'Quincy', codename: '' },
      { name: 'Charlotte', codename: '' },
      { name: 'Cheyenne', codename: '' },
      { name: 'Bridget', codename: '' },
      { name: 'Aaron', codename: '' },
      { name: 'Hunter', codename: '' },
      { name: 'Niko', codename: '' },
      { name: 'Marshall', codename: '' },
      { name: 'Edger', codename: '' },
      { name: 'Bronwyn', codename: '' },
      { name: 'Jonas', codename: '' },
      { name: 'Lincoln', codename: '' },
      { name: 'Jorge', codename: '' },
      { name: 'Jacob', codename: '' },
      { name: 'Anthony', codename: '' },
      { name: 'Starkey', codename: '' },
      { name: 'Marlane', codename: '' },
      { name: 'Issac', codename: '' },
      { name: 'Carson', codename: '' },
      { name: 'Sydney', codename: '' },
      { name: 'Zach', codename: '' },
      { name: 'Natalia', codename: '' },
    ],
  },
  {
    category: "Elementary",
    members: [
      { name: 'Josh Noble', codename: 'Mini Blitz' },
      { name: 'Matt Lihpai', codename: 'Glow' },
      { name: 'Jose Rodriguez', codename: 'Sonic' },
      { name: 'Jose Chavez', codename: '' },
      { name: 'Tayton Baker', codename: 'Flashpoint' },
      { name: 'Michael', codename: '' },
      { name: 'Thomas', codename: '' },
      { name: 'Veronica Teaford', codename: 'Crystal' },
      { name: 'Erica Teaford', codename: 'Mist' },
      { name: 'Nate Greene', codename: 'Bolt' },
      { name: 'Ivan Aparicio', codename: 'Shadow' },
      { name: 'Kaden Hansen', codename: 'Sparkle' },
      { name: 'Nick', codename: 'Whirlwind' },
      { name: 'Bridger', codename: 'Rune' },
      { name: 'Noah', codename: 'Torrent' },
      { name: 'Elise', codename: 'Glacier' },
      { name: 'Brigdan', codename: 'Ember' },
      { name: 'Addie', codename: 'Aurora' },
      { name: 'Dustin Khong', codename: 'Iron Spark' },
      { name: 'Kason', codename: 'Zephyr' },
      { name: 'Kody', codename: 'Blizzard' },
      { name: 'Lupa', codename: 'Vapor' },
      { name: 'Shanna', codename: 'Radiance' },
      { name: 'Elizabeth', codename: 'Frost' },
      { name: 'Kason', codename: '' },
      { name: 'Kaia', codename: '' },
      { name: 'Abby', codename: '' },
      { name: 'Gabe', codename: '' },
      { name: 'Raven', codename: '' },
      { name: 'Cade', codename: '' },
      { name: 'Grace', codename: '' },
      { name: 'Kalie', codename: '' },
      { name: 'Mikeal', codename: '' },
      { name: 'Sierra', codename: '' },
    ],
  },
  {
    category: "Acquaintances",
    members: [
      { name: 'Sheryl', codename: 'Sage' },
      { name: 'Krystal', codename: 'Prism' },
      { name: 'Deb', codename: 'Oracle' },
      { name: 'Jack Smith', codename: 'Sentinel' },
      { name: 'Dustin Edmonds', codename: 'Falcon' },
    ],
  },
];

// 🎯 Generate member list with actual superhero codenames
const fullLegionairesList = memberCategories.flatMap((categoryData, categoryIndex) => {
  return categoryData.members.map((member, memberIndex) => {
    const memberData = legionImages[member.name] || { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false };
    return {
      name: member.name,
      codename: member.codename, // Use the superhero codename here
      category: categoryData.category, // Store category separately
      screen: `Member${categoryIndex * 100 + memberIndex + 1}`,
      position: [Math.floor(memberIndex / 3), memberIndex % 3],
      ...memberData,
    };
  });
});

export default fullLegionairesList;