// 🎯 Static mapping of character images for Legionaires
const legionImages = {
  'Mason Erickson': { image: require('../../assets/Armor/MasonEPlaceHolder.jpg'), clickable: true },
  'Davis Clark': { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  'Cody Cline': { image: require('../../assets/Armor/CodyPlaceHolder.jpg'), clickable: true },
  'Kinnley Cline': { image: require('../../assets/Armor/KinnleyPlaceHolder.jpg'), clickable: true },
  'Cassidy Cline': { image: require('../../assets/Armor/CassidyPlaceHolder.jpg'), clickable: true },
  'Jack Smith': { image: require('../../assets/Armor/JackPlaceHolder.jpg'), clickable: true },
  Dylan: { image: require('../../assets/Armor/DylanPlaceHolder.jpg'), clickable: true },
  'Jessica Fisher': { image: require('../../assets/Armor/JessicaFPlaceHolder.jpg'), clickable: true },
  'Dustin Edmonds': { image: require('../../assets/Armor/DustinEPlaceHolder.jpg'), clickable: true },
  'Justin Platt': { image: require('../../assets/Armor/JustinPlaceHolder2.jpg'), clickable: true },
  'Zack Dustin': { image: require('../../assets/Armor/ZackPlaceHolder2_cleanup.jpg'), clickable: true },
  'Josh Noble': { image: require('../../assets/Armor/JoshNoblePlaceHolder.jpg'), clickable: true },
  'Will Knight': { image: require('../../assets/Armor/WillKPlaceHolder.jpg'), clickable: true },
  Christian: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  John: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Jose: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Matt: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Anthony: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Miles: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Cieanna: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Natalie: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Kanyon: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Emily: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Jarom: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Avery: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  'Kennedy Carman': { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Sydney: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  'Hunter': { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  'Cami Webb': { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  'Spencer Hill': { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Clayton: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  'Spencer L': { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  'Malia Holley': { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Mika: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Jason: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Allysa: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Josh: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  'John 1': { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  'John 2': { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Abby: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Tagun: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  'Adam Ledger': { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Sam: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  'Kaden Hanson 1': { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  'Sam Philops': { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  'Carter Olsen': { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  'Issac Philops': { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Hayden: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  'Parker Gold': { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  'Gabe Parker': { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  'Sanford Duncan': { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Lizzy: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Kyle: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Ivan: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Grace: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  'Kaden Hansen 2': { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Kaia: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Erica: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Veronica: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Elizabeth: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Shanna: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Lupa: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Kody: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  'Nate Greene': { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Nick: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Thomas: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Kason: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Bridger: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Addie: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Brigdon: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Noah: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Elsie: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Mason: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  'Emery Clark': { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Xzavier: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Quinton: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  'Quinton C': { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  Quincy: { image: require('../../assets/Armor/PlaceHolder.jpg'), clickable: false },
  };
  
  export default legionImages;
  