const LegionairesMembers = [
    { name: 'Leader Name', codename: 'Legion Alpha', screen: 'Leader', clickable: false, position: [0, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'Member 1', codename: 'Legion Beta', screen: 'Member1', clickable: false, position: [0, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'Member 2', codename: 'Legion Gamma', screen: 'Member2', clickable: false, position: [1, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'Member 3', codename: 'Legion Delta', screen: 'Member3', clickable: false, position: [1, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'Member 4', codename: 'Legion Epsilon', screen: 'Member4', clickable: false, position: [1, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [2, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [2, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [3, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [3, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [3, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [4, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [4, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [4, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [5, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [5, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [5, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [6, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [6, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [6, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [7, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [7, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [7, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [8, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [8, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [8, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [9, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [9, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [9, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [10, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [10, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [10, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [11, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [11, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [11, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [12, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [12, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [12, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [13, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [13, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [13, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [14, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [14, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [14, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [15, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [15, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [15, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [16, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [16, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [16, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [17, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [17, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [17, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [18, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [18, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [18, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [19, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [19, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [19, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [20, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [20, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [20, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [21, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [21, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [21, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [22, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [22, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [22, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [23, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [23, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [23, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [24, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [24, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [24, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [25, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [25, 1], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: 'TBA', codename: '???', screen: '', clickable: false, position: [25, 2], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },
    { name: '', codename: '', screen: '', clickable: false, position: [26, 0], image: require('../../assets/Armor/DefaultPlaceholder.jpg') },

  ];
  
  export default LegionairesMembers;
  